# Generated by Django 2.0.6 on 2018-07-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180716_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='e_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='patients',
            name='s_date',
            field=models.DateTimeField(),
        ),
    ]
