# Generated by Django 2.0.6 on 2018-07-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180716_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='e_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patients',
            name='s_date',
            field=models.DateField(),
        ),
    ]
