# Generated by Django 2.0.6 on 2018-07-16 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180716_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='e_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='s_date',
            new_name='start_date',
        ),
    ]
