# Generated by Django 2.0.6 on 2018-07-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180716_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=15),
        ),
    ]
