# Generated by Django 2.0.6 on 2018-07-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180717_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='comments_other',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='identification',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='referrer',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='patients',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
