# Generated by Django 2.0.6 on 2018-07-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180720_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='doctor',
            field=models.CharField(blank=True, choices=[('BEA', 'Beatrous'), ('CAM', 'Campbell'), ('DRK', 'Drake'), ('HOB', 'Hobeika'), ('PNK', 'Pinkston'), ('SAN', 'Sanford')], max_length=30),
        ),
        migrations.AlterField(
            model_name='patients',
            name='dosimetrist',
            field=models.CharField(blank=True, choices=[('TAT', 'Tatum'), ('HUN', 'Hunter'), ('MAP', 'Maples')], max_length=30),
        ),
        migrations.AlterField(
            model_name='patients',
            name='facility',
            field=models.CharField(blank=True, choices=[('TUS', 'Tuscaloosa'), ('WIN', 'Winfield'), ('JAS', 'Jasper'), ('DEM', 'Demopolis'), ('ANN', 'Anniston'), ('FTP', 'Fort Payne'), ('SYL', 'Sylacauga'), ('MON', 'Montgomery'), ('GAD', 'Gadsden')], max_length=3),
        ),
        migrations.AlterField(
            model_name='patients',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('I', 'Inactive')], max_length=15),
        ),
    ]
