# Generated by Django 2.0.6 on 2018-08-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20180720_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='doctor',
            field=models.CharField(blank=True, choices=[('Beatrous', 'Beatrous'), ('CAM', 'Campbell'), ('DRK', 'Drake'), ('HOB', 'Hobeika'), ('PNK', 'Pinkston'), ('SAN', 'Sanford')], max_length=30),
        ),
    ]
