# Generated by Django 2.0.6 on 2018-08-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20180806_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
